### ISSUE TITLE
Problem with scale for currency/JPY

### ISSUE THREAD

**Issue by nicolascepeda** [clojurewerkz/money#10]
I am having some issues while trying to generate an amount of JPY of 1000:

(ma/amount-of clojurewerkz.money.currencies/JPY 1500)

Going straight to Joda Money works:

(org.joda.money.BigMoney/.of clojurewerkz.money.currencies/JPY 15000)

I assume the problem is with the implementation, which expects an amount of type ^double instead of ^BigDecimal.

**Comment by nicolascepeda** [comment]
I resolved the issue by using ^BigDecimal and using BigMoney instead: 
(.toMoney (BigMoney/of unit amount))

Hope this helps,
Regards

**Comment by michaelklishin** [comment]
Sounds like an API change in Joda Money.

**Comment by michaelklishin** [comment]
From [Money javadoc](http://joda-money.sourceforge.net/apidocs/org/joda/money/Money.html):

```
Every currency has a certain standard number of decimal places. This is typically 2 (Euro, British Pound, US Dollar) but might be 0 (Japanese Yen), 1 (Vietnamese Dong) or 3 (Bahrain Dinar). The Money class is fixed to this number of decimal places.
```

Also note that `amounts/of-major` works just fine for JPY 1500. We will consider using `BigMoney` but this would be a significant breaking change in this library.
