### ISSUE TITLE
multiply/divide with BigDecimal

### ISSUE THREAD

**Issue by jgeraerts** [clojurewerkz/money#20]
This clojure wrapper uses type hints to make the multiplier explicitly a double, probably to avoid reflection warnings. However the joda money java library also has a multiplied by method taking a [BigDecimal ](http://www.joda.org/joda-money/apidocs/org/joda/money/Money.html#multipliedBy-java.math.BigDecimal-java.math.RoundingMode- ) as multiplier. Currently this cannot be used from this library. 

I'm willing to add this functionality, but it is unclear to me how to proceed in a idiomatic way:

* add a second methodname implying the type, e.g. multiply-by-bigdecimal or
* add a conditional check on the type in the current multiply method, adding typehints in the dispatch to the joda time library itself or
* replace the multiply function with a multimethod dispatching on type (slight variant of the above) or
* remove the typehints completely (like minus/plus)

**Comment by michaelklishin** [comment]
Joda Time has "type hints" (signatures) by definition ;) You can use a single function that then dispatches to a protocol (and not a multi-method), where each implementation has a type hint.

**Comment by jgeraerts** [comment]
And then swap the arguments in the Protocol function so i can dispatch on the multiplier type?

**Comment by michaelklishin** [comment]
Simply delegate to the protocol function. It should avoid reflection (which is the point of type hints).

**Comment by jgeraerts** [comment]
So for example your current function `multiply`

```
(defn ^Money multiply
  ([^Money money ^double multiplier]
     (.multipliedBy money multiplier (cnv/to-rounding-mode nil)))
  ([^Money money ^double multiplier rounding-mode]
     (.multipliedBy money multiplier (cnv/to-rounding-mode rounding-mode))))
```

would become 

````
(defprotocol AmountOps
  (op-multiply [multiplier money rounding-mode]))

(extend-protocol AmountOps
  double
  (op-multiply [multiplier ^Money money rounding-mode]
    (.multipliedBy money multiplier rounding-mode))
  java.math.BigDecimal
  (op-multiply [multiplier ^Money money rounding-mode]
    (.multipliedBy money multiplier rounding-mode)))

(defn ^Money multiply
  ([^Money money ^double multiplier]
     (op-multiply multiplier money (cnv/to-rounding-mode nil)))
  ([^Money money ^double multiplier rounding-mode]
     (op-multiply multiplier money (cnv/to-rounding-mode rounding-mode))))
```

And then ofcourse similar for the other operations. The only thing i feel dirty about is the parameter order in the protocol, especially for `op-minus` it gets counter intuitive.

**Comment by michaelklishin** [comment]
That actually might be nicer than what I had in mind. We still need to drop the type hint from `multiply`.

**Comment by jgeraerts** [comment]
alright, i'll work it out.
