### ISSUE TITLE
build-formatter is not usable from outside

### ISSUE THREAD

**Issue by jwr** [clojurewerkz/money#25]
The `build-formatter` macro uses `new-builder`, but `new-builder` is marked as `^:private`, so `build-formatter` is not usable from outside the clojurewerkz `format.clj` file.

As a result, it is rather difficult to build new formatters in applications (my specific problem was that I need monetary amounts printed *without* currency symbols).

**Comment by michaelklishin** [comment]
Please submit a PR, `new-builder` can be made public if needed.
