### ISSUE TITLE
New release into Clojars

### ISSUE THREAD

**Issue by mt3593** [clojurewerkz/money#31]
Hi would it be possible to push a new release to Clojars

**Comment by michaelklishin** [comment]
Yes, now that we support the latest Joda Money before 0.12, a new release is definitely needed before we move to either 1.0 or Java Money.

**Comment by cfclrk** [comment]
Any ideas when a new release might be pushed?

**Comment by mt3593** [comment]
Sorry to pester, but any update on the release?

**Comment by michaelklishin** [comment]
[`1.11.0` is up on Clojars](https://clojars.org/clojurewerkz/money). Sorry that it's taken me so long.
